### ISSUE TITLE
PhyloMultivariateBrownianTest failed randomly

### ISSUE THREAD

**Issue by walterxie** [LinguaPhylo/linguaPhylo#162]
Perhaps it should fix the seed.

**Comment by walterxie** [comment]
fix seed

**Comment by kche309** [comment]
A related issue is mentioned in https://github.com/LinguaPhylo/linguaPhylo/issues/152. 
From my previous investigation, all random methods should share the same generator, e.g., `Utils.random` or pass in the generator from `Utils.random`. 

https://github.com/LinguaPhylo/linguaPhylo/blob/59b3d443be61b3dd9d8d14b5f1b14fc2e410a55d/lphy/src/main/java/lphy/core/distributions/Utils.java

The gamma sampler currently doesn't use the same random generator. 
I suggest we use `GammaDistribution(RandomGenerator rng, double shape, double scale)` instead of  `GammaDistribution(double shape, double scale)`.
```
    public static double randomGamma(double shape, double scale) {
        return new GammaDistribution(shape, scale).sample();
    }
```

An alternative is to use reflection to make sure the random generator is only created once, and used everywhere else.

**Comment by walterxie** [comment]
`Utils.random` is static, so the best way is to `setSeed` in a lphy function.
