### ISSUE TITLE
lphystudio crashes with java exception on linux

### ISSUE THREAD

**Issue by bredelings** [LinguaPhylo/linguaPhylo#336]
Hi,

I just tried lphy-studio-1.4.1, and I get the following error when running `bin/lphystudio`:

```
$ bin/lphystudio 
Gtk-Message: 15:02:10.946: Failed to load module "canberra-gtk-module"
Exception in thread "main" java.lang.ExceptionInInitializerError
Caused by: java.lang.UnsupportedOperationException: Taskbar API is not supported on the current platform
	at java.desktop/java.awt.Taskbar.getTaskbar(Taskbar.java:217)
	at lphystudio@1.4.1/lphystudio.app.LinguaPhyloStudio.<clinit>(LinguaPhyloStudio.java:45)
```

I tried running `java -p lib -m lphystudio` in 1.4.0, and this does seem to work.  However, running it in the 1.4.1 release yields the same error about the taskbar.

-BenRI

**Comment by walterxie** [comment]
Hi @bredelings the problem is due to Java Desktop not well supported by Linux. I made a quick fix and will test it before the next release. In addition:

- Would you like to report your OS version and Java version?
- I have a feeling it may let you use 1.4.1, if you could install `gtk3`:  https://itslinuxfoss.com/fix-failed-load-module-canberra-gtk-module-error/, https://askubuntu.com/questions/342202/failed-to-load-module-canberra-gtk-module-but-already-installed

**Comment by bredelings** [comment]
Hi Walter,

I will try it.  But the issue with Canberra is just a warning.  The error
is afterwards and is not related to Canberra.

-BenRI

**Comment by bredelings** [comment]
This seems to be fixed now.
