### ISSUE TITLE
Resampling duplicates part of the model?

### ISSUE THREAD

**Issue by bredelings** [LinguaPhylo/linguaPhylo#342]
Hi,

I tried loading the following script in LPhy 1.4.0
```
weights = [100.0,100.0,100.0,1000.0];
n ~ Geometric(p=0.5);
rates ~ Dirichlet(conc=[100.0,100.0,100.0,1000.0], replicates=1+n);
g = length(rates);
v = rates[0];
L = length(v);
```

This worked OK, but if I press the "sample" button, this results in some weird behavior:

![image](https://user-images.githubusercontent.com/140268/236365124-55b64037-d58c-48c9-af42-43048c0e8815.png)

You can see that "rates" now occurs in the model twice!

If I continue to press "sample", then there is only one "rates", but still two instances of "v".

**Comment by walterxie** [comment]
I cannot replicate this in the master branch now. The bug may have been fixed by other issues.  

<img width="1667" alt="Screenshot 2023-05-05 at 4 53 41 PM" src="https://user-images.githubusercontent.com/5743014/236380145-4d610ae1-e08c-4fa5-af23-dcffd128199d.png">

**Comment by walterxie** [comment]
I cannot guarantee, but I will try to make a pre-release of 1.4.2 next week, if Alexei agrees.

**Comment by alexeid** [comment]
Did you click sample multiple times?

From: Walter ***@***.***>
Date: Friday, 5 May 2023 at 4:55 PM
To: LinguaPhylo/linguaPhylo ***@***.***>
Cc: Subscribed ***@***.***>
Subject: Re: [LinguaPhylo/linguaPhylo] Resampling duplicates part of the model? (Issue #342)

I cannot replicate this in the master branch now. The bug may have been fixed by other issues.

[Image removed by sender. Screenshot 2023-05-05 at 4 53 41 PM]<https://user-images.githubusercontent.com/5743014/236380145-4d610ae1-e08c-4fa5-af23-dcffd128199d.png>

**Comment by walterxie** [comment]
I set `Reps: 10`

**Comment by bredelings** [comment]
Hi walter, thanks for the fixes.

I tried building the master branch from source, and this problem does indeed seem to be fixed.

-BenRI
