### ISSUE TITLE
replicates should >= 0

### ISSUE THREAD

**Issue by walterxie** [LinguaPhylo/linguaPhylo#350]
Add the validation to check if `replicates >= 1` when using IID. Otherwise throw `IllegalArgumentException` (Runtime) and catch at the top level.

Update to `replicates >= 0`

**Comment by bredelings** [comment]
Hmm...  requiring replicates to be >=1 makes it impossible to have the number of replicates be random.

If that is intentional, perhaps you should also check that replicates is random and complain about that as well?

Also, perhaps you should introduce an `iid` distribution for when people want to allow replicates to be 0 or 1?

**Comment by walterxie** [comment]
You can draw it from a Poisson distribution, and set min=1. This is an example from Alexei:

```
// replicates = 1, 2, 3, ...
k ~ Poisson(lambda=1.0, min=1);
pi ~ Dirichlet(conc=[1, 1, 1, 1], replicates=k);
L = length(pi);
```

But I cannot figure out what replicates=0 means?
