### ISSUE TITLE
Narrative says Pr(null|....)

### ISSUE THREAD

**Issue by bredelings** [LinguaPhylo/linguaPhylo#385]
In the RSV2 "Narrative" pane, we see

```
Pr(pi, kappa, r, mu, psi, Theta | codon) = \prod_i=0^2 P(null | psi, mu, Q_i) .....
```

Probably `null` should be `codon`?

**Comment by walterxie** [comment]
Currently, we are undergoing a complex refactoring process to separate the core functionality from the standard library. Once this refactoring is completed, I will revisit this issue.

**Comment by walterxie** [comment]
When the generator is VectorizedDistribution, data clamping requires to wrap the list of component RandomVariable into VectorizedRandomVariable, so that the equation and narrative can be generated properly.

<img width="678" alt="Screenshot 2023-06-07 at 3 35 30 PM" src="https://github.com/LinguaPhylo/linguaPhylo/assets/5743014/5e80e642-003e-45ad-90a2-0945adf55a05">

**Comment by walterxie** [comment]
Github action has a problem again. All tests are passed in local.

**Comment by walterxie** [comment]
7352f6d3e514f11b2f111a121d18bc364b0ace87 and 4d7b36f5acdd1e3aace5fa4da76fa0567b740144
