### ISSUE TITLE
Implement support for for-loops in parser.

### ISSUE THREAD

**Issue by alexeid** [LinguaPhylo/linguaPhylo#63]
Support for for-loops will allow for much more succinct models that involve many data partitions, such as hundreds of independent loci under the same coalescent model.

**Comment by alexeid** [comment]
I will not implement this. Implicit vectorization support is enough for all the models implemented to date and is much cleaner than for loops.

**Comment by bredelings** [comment]
Hmm.... except for this one:  https://github.com/LinguaPhylo/linguaPhylo/blob/master/examples/skylineCoalescent.lphy

**Comment by alexeid** [comment]
> Hmm.... except for this one: https://github.com/LinguaPhylo/linguaPhylo/blob/master/examples/skylineCoalescent.lphy

Hey Ben! I backed out of supporting for loops because I decided it was against my design goal to allow allow a more procedural style. I am aiming for it to be a completely declarative language. It is aimed at model specification and all the use cases that I have looked at work nicely with the automatic vectorization idioms that I have implemented. Of course I am happy to hear your opinion :)

**Comment by bredelings** [comment]
Hey Alexei!  The language looks really nice and easy to read  - I like it :-)  I'm thinking about switching lexers so that I can handle unicode characters after seeing Greek letters in your model files.

This is just my opinion, but in case it is helpful or offers another perspective, here goes:

A declarative language sounds great.  I don't really like for loops (or other imperative language constructs) either.  In my opinion there are a few different language approaches, and each has pros and cons.  On the plus side, I think the declarative approach make it a lot simpler to represent models and reason about them.  On the con side, a declarative language probably means a less expressive language, and so anything that needs loops will have to be written in Java.  This could be seen as simply pushing the imperative part into Java.

Functional languages seem to be in between imperative and purely declarative.  I'm taking the functional language route, because I'm valuing expressivity above simplicity & clarity.

One way you could increase expressivity while still being declarative would be to introduce a `map` function, but write the `map` function in java.  For example, instead of `for(i in 1:10) { y[i] := exp(z[i]) }` you could have `y = map(exp,z)`.

This still wouldn't handle the `ExpMarkovChain` example, because in that example each element `N[i]` depends on the previous element.  So you if you want to change the distribution from `Exp` to something else, you would have to write a new Java function.  That is the main thing that I don't like.  As a way to get around that, you could also write a more general `MarkovChain` function (in Java) that takes an initial state, a chain length, _and_ a function like `Exp` from a state to the distribution of the next state.  Then you could  change `Exp` to some other distribution without going back to java.

What do you think?

**Comment by bredelings** [comment]
Another thought: when people write models on a white board, they _do_ use subscripts, as in `y[i] = log(z[i])` or things like that.  But these models are declarative, not imperative.   So maybe its possible to have a  _declarative_ "for" statement -- it could be called a "forall" statement.

So if you have `forall(i in 1:10) { y[i] = log(z[i]) }` then this would be different than a revbayes-like `for`-statement in that the different iterations are not sequential, but are (logically) simultaneous.  The iterations do not actually depend on each other, but only on `i`.  So, the forall statement wouldn't have side-effects.

This would rule out rev-bayes-like for loops such as the following, for several reasons:
```
j=0
for(i in 1:10)
{
  j = j + 1.0
  y ~ normal(j,1.0)
}
```
* `j = j + 1.0` isn't declarative 
* iterations aren't simultaneous.

In loops like `forall(i in 2:10) { N[i] ~ Exp(N[i-1]) }` you would need to handle the fact that some "iterations" reference variables created in other "iterations".  However, since the loop body is only declarative for each value of `i`, and all the "iterations" are simultaneous, you could 
1. first, create all the variable names (the N[i]) for all values of `i`.  In fact, if all loop ranges are non-random, you can enumerate all variables pretty easily.
2. second, actually define the right-hand-side (after the "=" or "~") for each variable, possibly referencing other variables.

**Comment by alexeid** [comment]
> One way you could increase expressivity while still being declarative would be to introduce a `map` function, but write the `map` function in java. For example, instead of `for(i in 1:10) { y[i] := exp(z[i]) }` you could have `y = map(exp,z)`.

Yes I have thought of introducing higher level functions, including the idea of being able to pass generators (random or deterministic functions) to those higher level functions. 

One higher level function, which is still quite low level, could, as you say, be MarkovChain, which would take a kernel distribution.

I like this approach, and I think it is better than writing endless similar things to ExpMarkovChain in Java, but I have been holding off in case a better idea materialised :)

**Comment by alexeid** [comment]
For a MarkovChain generator you could have something like:

`N ~ MarkovChain(kernel=Exp(), initial=1.0, length=10)`

or

`N ~ MarkovChain(kernel=Normal(stdev=1.0), initial=1.0, length=10)`

The generative distribution that is passed as the kernel is primed with the parameters that won't be filled by the previous element.

I guess this would lead naturally to the ability to define new generators/functions like:

```
UnitSDNormal = Normal(stdev=1.0);
N ~ MarkovChain(kernel=UnitSDNormal(), initial=1.0, length=10)
```

**Comment by bredelings** [comment]
Yeah, that does seem a lot better than ExpMarkovChain.

The "generator" concept seems to group things that I think of separately.
* python functions that "yield" results -- these can yield a possibly infinite sequence of results.
* distributions -- you can sample a possibly infinite sequence of results from a distribution
* lists -- you can draw a possibly infinite sequence of results from a list.
However, these things yield sequences of results in different ways, so it seems odd (to me) to group them.  However, maybe that's because I'm thinking of them in terms of a type system, instead of an api.  Functions don't really seem like generators to me.

**Comment by bredelings** [comment]
Regarding defining new functions:
```
UnitSDNormal = Normal(stdev=1.0);
```
This is basically a syntax for defining lambda functions / anonymous functions.  I kind of like it, but it seems less expressive that you might need.  For example, if you have an alternative syntax like `mu -> Normal(mu,1)` then
* If you have `tan(asin())` -- is this `x -> tan(asin(x))` or `tan(x->asin(x))`? Let's assume it means `tan(x->asin(x))`, because otherwise you could never directly pass a lambda function to another function.
* In that case then you _can_ represent `x->sin(x)` as `sin()`, but you _can't_ represent `x->sin(x)+1` at all.

**Comment by alexeid** [comment]
LPhy Generators are anything that produce a Value. Only generators can produce values. I think there are two types:

(1) Distributions
(2) Deterministic functions

Each generator takes zero or more values and produces an output. When parameters remain the same, then subsequent outputs from a distribution are random and i.i.d. Whereas in the case of functions the output is always the same with subsequent calls using the same input parameter values.

**Comment by bredelings** [comment]
Oh, I see. I guess that makes sense.

If a generator is a distribution with all arguments supplied, is it
possible for it to return as a value the distribution itself, instead of a
sample from the distribution?

This would be needed for generators that need distributions as arguments,
including:

* discretize(distribution, n_bins)
* dirichlet_process(n_samples, alpha, base_distribution)
* mixture_dist(distributions, weights)
* iid(n_samples, base_distribution)
etc.

**Comment by bredelings** [comment]
BTW, have you seen this?

Practical Probabilistic Programming with Monads -
http://mlg.eng.cam.ac.uk/pub/pdf/SciGhaGor15.pdf

In this syntax, "d <- normal 0 1" draws a value from the distribution,
whereas "let d = normal 0 1" references the distribution itself.

(Also, in case it's useful, I just saw Blang today for the first time.
https://www.stat.ubc.ca/~bouchard/blang/ . Not sure I like it, but they
claim to have phylogenies.)

**Comment by alexeid** [comment]
I saw Blang about a year ago but didn't look at it as closely as I should have. Actually Xtext (which was used to build it) looks really cool, so now I am wondering how hard it would be to build a parser for LPhy in Xtext :) I think I might give that a go today.

As far the Blang goes: it seems a bit more verbose then I would want. I purposefully avoid things like variable declarations since they can be inferred and adding there requirement to the language specification just adds clutter and the potential to more easily overwhelm a user that is not used to reading code.
